tap "homebrew/bundle"
tap "homebrew/services"
tap "railwaycat/emacsmacport"
tap "puma/puma"
brew "logrotate"
brew "mysql", restart_service: true
brew "postgresql@15", restart_service: true
brew "redis", restart_service: true
brew "wxwidgets"
brew "puma/puma/puma-dev"
cask "1password"
cask "alfred"
cask "anki"
cask "arc"
cask "cleanshot"
cask "dash"
cask "deepl"
cask "dropbox"
cask "emacs-mac"
cask "figma"
cask "google-chrome"
cask "hey"
cask "iterm2"
cask "livebook"
cask "notion"
cask "obsidian"
cask "postman"
cask "raycast"
cask "rectangle"
cask "slack"
cask "spotify"
cask "viscosity"
cask "visual-studio-code"
cask "wechatwebdevtools"
cask "zoom"
